### ISSUE TITLE
Magic (Drop Party) Tree Leaves & Logs

### ISSUE THREAD

**Issue by DarkArc** [Skelril/Skree-Assets#11]

**Comment by pyroclown** [comment]
How to leaves that quickly cycle through different images of items sound

**Comment by DarkArc** [comment]
Uh... I don't know about that, it would imply dropping those items... and I don't think we want to imply a specific item drop on the texture.

**Comment by pyroclown** [comment]
The cycle would be too quick for anyone to be able to tell what the item is that is displayed. They will only be able to tell that they are items
